name: JueJin AutoClock Action

on:
  push:
    # 仅main分支提交触发
    branches: [main]
  schedule:
  # 定时任务,每天9：11触发(由于服务器是UTC时间，需要减去8小时)
    - cron: '11 1 * * *'

jobs:
  # 构建ID
  build:
    # 说明
    name: build
    # 构建运行的系统环境，GitHub提供
    runs-on: ubuntu-latest
    # 构建步骤
    steps:
      - uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn
      - run: yarn build
      - run: date
      - name: Run script
        run: npx cross-env cookies='$COOKIE' receiver='$RECEIVER' sender='$SENDER' pass='$MAIL_PASS' node dist/index.js
        env:
          COOKIE: ${{secrets.JUE_JIN_COOKIES}}
          SENDER: ${{secrets.SENDER}}
          RECEIVER: ${{secrets.RECEIVER}}